language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip setuptools wheel

install:
  - travis_wait travis_retry pip install -r requirements.txt cpplint
  - travis_retry python setup.py build install

script:
  - cpplint --linelength 100 nmsbind.cc
  - python setup.py test

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
