language: cpp
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
  - os: osx
    env: PYTHON=3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
  fi
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry python setup.py build install

script:
- python tests/nmsbind_test.py

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
